#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.vivwe.entity
  mapperLocations: classpath:com/vivwe/mapper/*.xml
